version: "3.7"

networks:
  default:
    name: takehome

services:
  postgres:
    image: postgres:13.4-alpine3.14
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432