image:
  file: .gitpod.dockerfile
# Commands to start on workspace startup
tasks:
  - name: docker-compose
    init: docker-compose pull
    command: docker-compose up
  - name: Backend
    init: |
      cd /workspace/slingshot-takehome/backend
      npm i
    command: |
      cd /workspace/slingshot-takehome/backend
      while ! psql postgres://postgres:password@127.0.0.1:5432 --pset=pager=off -c 'SELECT 1'; do echo 'waiting for postgres'; sleep 1; done
      npm run dev
  - name: Frontend
    init: cd /workspace/slingshot-takehome/frontend && npm i
    command: cd /workspace/slingshot-takehome/frontend && npm run start
# Ports to expose on workspace startup
ports:
  - port: 3000
    onOpen: open-browser
    visibility: public
  - port: 3001
    onOpen: open-browser
    visibility: public
github:
  prebuilds:
    # enable for the default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: true
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: true
    # add a check to pull requests (defaults to true)
    addCheck: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: true
    # add a "Review in Gitpod" button to the pull request's description (defaults to false)
    addBadge: false