# image: node:16.9.1-alpine3.14
github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true
# Commands to start on workspace startup
tasks:
  - name: Backend
    init: cd backend || npm i
    command: cd backend || npm run dev
  - name: Frontend
    init: cd frontend || npm i
    command: cd frontend || npm run start
# Ports to expose on workspace startup
ports:
  - port: 3000
    onOpen: open-preview